version: "3"

services:
  front:
    image: "api-front"
    build: .
    container_name: "React"
    command: npm start
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./:/usr/app